version: '3.8'
services:
  mysql-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  flask-app:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - mysql-db

volumes:
  db_data:

